AWSTemplateFormatVersion: '2010-09-09'
Description: Tutorial for Angular and PWA
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  HostingBucket:
    Description: Stores static website content
    Type: AWS::S3::Bucket

  HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: HostingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref HostingBucket
                - '/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontDistribution:
    Description: Angular Tic Tac Toe Game
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: !Sub 'S3-${AWS::StackName}-root'
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: !GetAtt HostingBucket.RegionalDomainName
            Id: !Sub 'S3-${AWS::StackName}-root'
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront OAI for ${AWS::StackName}
